# permissions for end users to view tokenmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tokenmap-viewer-role
rules:
- apiGroups:
  - k8ssandra.io
  resources:
  - tokenmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8ssandra.io
  resources:
  - tokenmaps/status
  verbs:
  - get
