# permissions for end users to edit tokenmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tokenmap-editor-role
rules:
- apiGroups:
  - k8ssandra.io
  resources:
  - tokenmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8ssandra.io
  resources:
  - tokenmaps/status
  verbs:
  - get
